### ISSUE TITLE
Core dump when number of histogram bins is greater than the length of a reference chromosome

### ISSUE THREAD

**Issue by rpkincaid** [fbreitwieser/bamcov#4]
I noticed that I was getting crashes when the number of histogram bins is greater than the length of a reference chromosome.

**Comment by fbreitwieser** [comment]
Thanks for reporting that, @rpkincaid . Should be fixed with the latest version - the maximum bin size for each sequence is its length.

**Comment by rpkincaid** [comment]
Thanks for the quick fix @fbreitwieser !
